// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"MicroEcom/sdk/models"
)

// CreateProductReader is a Reader for the CreateProduct structure.
type CreateProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateProductCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateProductBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateProductInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /products] createProduct", response, response.Code())
	}
}

// NewCreateProductCreated creates a CreateProductCreated with default headers values
func NewCreateProductCreated() *CreateProductCreated {
	return &CreateProductCreated{}
}

/*
CreateProductCreated describes a response with status code 201, with default header values.

New product response with the product ID
*/
type CreateProductCreated struct {
	Payload *models.GenericMessage
}

// IsSuccess returns true when this create product created response has a 2xx status code
func (o *CreateProductCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create product created response has a 3xx status code
func (o *CreateProductCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create product created response has a 4xx status code
func (o *CreateProductCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create product created response has a 5xx status code
func (o *CreateProductCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create product created response a status code equal to that given
func (o *CreateProductCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create product created response
func (o *CreateProductCreated) Code() int {
	return 201
}

func (o *CreateProductCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /products][%d] createProductCreated %s", 201, payload)
}

func (o *CreateProductCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /products][%d] createProductCreated %s", 201, payload)
}

func (o *CreateProductCreated) GetPayload() *models.GenericMessage {
	return o.Payload
}

func (o *CreateProductCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateProductBadRequest creates a CreateProductBadRequest with default headers values
func NewCreateProductBadRequest() *CreateProductBadRequest {
	return &CreateProductBadRequest{}
}

/*
CreateProductBadRequest describes a response with status code 400, with default header values.

Error response for various operations
*/
type CreateProductBadRequest struct {
	Payload *models.GenericError
}

// IsSuccess returns true when this create product bad request response has a 2xx status code
func (o *CreateProductBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create product bad request response has a 3xx status code
func (o *CreateProductBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create product bad request response has a 4xx status code
func (o *CreateProductBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create product bad request response has a 5xx status code
func (o *CreateProductBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create product bad request response a status code equal to that given
func (o *CreateProductBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create product bad request response
func (o *CreateProductBadRequest) Code() int {
	return 400
}

func (o *CreateProductBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /products][%d] createProductBadRequest %s", 400, payload)
}

func (o *CreateProductBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /products][%d] createProductBadRequest %s", 400, payload)
}

func (o *CreateProductBadRequest) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *CreateProductBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateProductInternalServerError creates a CreateProductInternalServerError with default headers values
func NewCreateProductInternalServerError() *CreateProductInternalServerError {
	return &CreateProductInternalServerError{}
}

/*
CreateProductInternalServerError describes a response with status code 500, with default header values.

Error response for various operations
*/
type CreateProductInternalServerError struct {
	Payload *models.GenericError
}

// IsSuccess returns true when this create product internal server error response has a 2xx status code
func (o *CreateProductInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create product internal server error response has a 3xx status code
func (o *CreateProductInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create product internal server error response has a 4xx status code
func (o *CreateProductInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create product internal server error response has a 5xx status code
func (o *CreateProductInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create product internal server error response a status code equal to that given
func (o *CreateProductInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create product internal server error response
func (o *CreateProductInternalServerError) Code() int {
	return 500
}

func (o *CreateProductInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /products][%d] createProductInternalServerError %s", 500, payload)
}

func (o *CreateProductInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /products][%d] createProductInternalServerError %s", 500, payload)
}

func (o *CreateProductInternalServerError) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *CreateProductInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
