// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"MicroEcom/sdk/models"
)

// GetProductsReader is a Reader for the GetProducts structure.
type GetProductsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProductsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProductsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 405:
		result := NewGetProductsMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetProductsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /products] GetProducts", response, response.Code())
	}
}

// NewGetProductsOK creates a GetProductsOK with default headers values
func NewGetProductsOK() *GetProductsOK {
	return &GetProductsOK{}
}

/*
GetProductsOK describes a response with status code 200, with default header values.

A list of products returned in the response
*/
type GetProductsOK struct {
	Payload []*models.Product
}

// IsSuccess returns true when this get products o k response has a 2xx status code
func (o *GetProductsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get products o k response has a 3xx status code
func (o *GetProductsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get products o k response has a 4xx status code
func (o *GetProductsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get products o k response has a 5xx status code
func (o *GetProductsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get products o k response a status code equal to that given
func (o *GetProductsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get products o k response
func (o *GetProductsOK) Code() int {
	return 200
}

func (o *GetProductsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products][%d] getProductsOK %s", 200, payload)
}

func (o *GetProductsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products][%d] getProductsOK %s", 200, payload)
}

func (o *GetProductsOK) GetPayload() []*models.Product {
	return o.Payload
}

func (o *GetProductsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProductsMethodNotAllowed creates a GetProductsMethodNotAllowed with default headers values
func NewGetProductsMethodNotAllowed() *GetProductsMethodNotAllowed {
	return &GetProductsMethodNotAllowed{}
}

/*
GetProductsMethodNotAllowed describes a response with status code 405, with default header values.

Error response for various operations
*/
type GetProductsMethodNotAllowed struct {
	Payload *models.GenericError
}

// IsSuccess returns true when this get products method not allowed response has a 2xx status code
func (o *GetProductsMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get products method not allowed response has a 3xx status code
func (o *GetProductsMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get products method not allowed response has a 4xx status code
func (o *GetProductsMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this get products method not allowed response has a 5xx status code
func (o *GetProductsMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this get products method not allowed response a status code equal to that given
func (o *GetProductsMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

// Code gets the status code for the get products method not allowed response
func (o *GetProductsMethodNotAllowed) Code() int {
	return 405
}

func (o *GetProductsMethodNotAllowed) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products][%d] getProductsMethodNotAllowed %s", 405, payload)
}

func (o *GetProductsMethodNotAllowed) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products][%d] getProductsMethodNotAllowed %s", 405, payload)
}

func (o *GetProductsMethodNotAllowed) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *GetProductsMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProductsInternalServerError creates a GetProductsInternalServerError with default headers values
func NewGetProductsInternalServerError() *GetProductsInternalServerError {
	return &GetProductsInternalServerError{}
}

/*
GetProductsInternalServerError describes a response with status code 500, with default header values.

Error response for various operations
*/
type GetProductsInternalServerError struct {
	Payload *models.GenericError
}

// IsSuccess returns true when this get products internal server error response has a 2xx status code
func (o *GetProductsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get products internal server error response has a 3xx status code
func (o *GetProductsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get products internal server error response has a 4xx status code
func (o *GetProductsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get products internal server error response has a 5xx status code
func (o *GetProductsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get products internal server error response a status code equal to that given
func (o *GetProductsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get products internal server error response
func (o *GetProductsInternalServerError) Code() int {
	return 500
}

func (o *GetProductsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products][%d] getProductsInternalServerError %s", 500, payload)
}

func (o *GetProductsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /products][%d] getProductsInternalServerError %s", 500, payload)
}

func (o *GetProductsInternalServerError) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *GetProductsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
