// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"MicroEcom/sdk/models"
)

// UpdateProductReader is a Reader for the UpdateProduct structure.
type UpdateProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateProductOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewUpdateProductNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateProductInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /products/{id}] updateProduct", response, response.Code())
	}
}

// NewUpdateProductOK creates a UpdateProductOK with default headers values
func NewUpdateProductOK() *UpdateProductOK {
	return &UpdateProductOK{}
}

/*
UpdateProductOK describes a response with status code 200, with default header values.

Updated product response with the product ID
*/
type UpdateProductOK struct {
	Payload *models.GenericMessage
}

// IsSuccess returns true when this update product o k response has a 2xx status code
func (o *UpdateProductOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update product o k response has a 3xx status code
func (o *UpdateProductOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update product o k response has a 4xx status code
func (o *UpdateProductOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update product o k response has a 5xx status code
func (o *UpdateProductOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update product o k response a status code equal to that given
func (o *UpdateProductOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update product o k response
func (o *UpdateProductOK) Code() int {
	return 200
}

func (o *UpdateProductOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /products/{id}][%d] updateProductOK %s", 200, payload)
}

func (o *UpdateProductOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /products/{id}][%d] updateProductOK %s", 200, payload)
}

func (o *UpdateProductOK) GetPayload() *models.GenericMessage {
	return o.Payload
}

func (o *UpdateProductOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateProductNotFound creates a UpdateProductNotFound with default headers values
func NewUpdateProductNotFound() *UpdateProductNotFound {
	return &UpdateProductNotFound{}
}

/*
UpdateProductNotFound describes a response with status code 404, with default header values.

Error response for various operations
*/
type UpdateProductNotFound struct {
	Payload *models.GenericError
}

// IsSuccess returns true when this update product not found response has a 2xx status code
func (o *UpdateProductNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update product not found response has a 3xx status code
func (o *UpdateProductNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update product not found response has a 4xx status code
func (o *UpdateProductNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update product not found response has a 5xx status code
func (o *UpdateProductNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update product not found response a status code equal to that given
func (o *UpdateProductNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the update product not found response
func (o *UpdateProductNotFound) Code() int {
	return 404
}

func (o *UpdateProductNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /products/{id}][%d] updateProductNotFound %s", 404, payload)
}

func (o *UpdateProductNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /products/{id}][%d] updateProductNotFound %s", 404, payload)
}

func (o *UpdateProductNotFound) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *UpdateProductNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateProductInternalServerError creates a UpdateProductInternalServerError with default headers values
func NewUpdateProductInternalServerError() *UpdateProductInternalServerError {
	return &UpdateProductInternalServerError{}
}

/*
UpdateProductInternalServerError describes a response with status code 500, with default header values.

Error response for various operations
*/
type UpdateProductInternalServerError struct {
	Payload *models.GenericError
}

// IsSuccess returns true when this update product internal server error response has a 2xx status code
func (o *UpdateProductInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update product internal server error response has a 3xx status code
func (o *UpdateProductInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update product internal server error response has a 4xx status code
func (o *UpdateProductInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this update product internal server error response has a 5xx status code
func (o *UpdateProductInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this update product internal server error response a status code equal to that given
func (o *UpdateProductInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the update product internal server error response
func (o *UpdateProductInternalServerError) Code() int {
	return 500
}

func (o *UpdateProductInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /products/{id}][%d] updateProductInternalServerError %s", 500, payload)
}

func (o *UpdateProductInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /products/{id}][%d] updateProductInternalServerError %s", 500, payload)
}

func (o *UpdateProductInternalServerError) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *UpdateProductInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
