basePath: /
consumes:
    - application/json
definitions:
    Product:
        properties:
            description:
                type: string
                x-go-name: Description
            id:
                format: int64
                type: integer
                x-go-name: ID
            name:
                type: string
                x-go-name: Name
            price:
                format: double
                type: number
                x-go-name: Price
            sku:
                type: string
                x-go-name: SKU
        type: object
        x-go-package: MicroEcom/db
info:
    description: '# Documentation for Product API'
    title: of Product API
    version: 1.0.0
paths:
    /products:
        get:
            operationId: getProducts
            responses:
                "200":
                    $ref: '#/responses/productsResponse'
            summary: GetProducts handles the retrieval of products.
            tags:
                - products
produces:
    - application/json
responses:
    productsResponse:
        description: A list of products returned in the response
        schema:
            items:
                $ref: '#/definitions/Product'
            type: array
schemes:
    - http
swagger: "2.0"
